import { ErrorExplanation, SupportedLanguage } from '../types';

export function getFileExtension(language: SupportedLanguage): string {
  switch (language) {
    case 'Python':
      return 'py';
    case 'JavaScript':
      return 'js';
    case 'Java':
      return 'java';
    case 'C++':
      return 'cpp';
    case 'C':
      return 'c';
    default:
      return 'txt';
  }
}

export function generateMarkdownReport(
  rawError: string,
  explanation: ErrorExplanation
): string {
  const date = new Date().toISOString();
  return `# DEVFIX Diagnostic Report: ${explanation.errorType}

**Language:** ${explanation.language}  
**Severity:** ${explanation.severity}  
**AI Confidence:** ${explanation.confidence}  
**Generated At:** ${date}

---

## 1. Raw Error Stack
\`\`\`
${rawError.trim()}
\`\`\`

---

## 2. What Happened?
${explanation.whatHappened}

---

## 3. Why Did It Happen?
${explanation.whyDidItHappen}

---

## 4. How Can I Fix It?
${explanation.howCanIFixIt}

---

## 5. Suggested Solution

${explanation.suggestedSolutionSummary ? `> **Summary:** ${explanation.suggestedSolutionSummary}\n` : ''}

### Problematic Code (Before)
\`\`\`${getFileExtension(explanation.language)}
${explanation.solution.before}
\`\`\`

### Corrected Code (After)
\`\`\`${getFileExtension(explanation.language)}
${explanation.solution.after}
\`\`\`

---
*Generated by DEVFIX – AI Error Explainer*
`;
}

export function downloadFile(filename: string, content: string, mimeType = 'text/plain'): void {
  const blob = new Blob([content], { type: `${mimeType};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
